version: '3.8'

services:
  postgres:
    image: postgres:latest  
    container_name: postgres_task_management
    environment:
      POSTGRES_USER: admin       
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: task_db     
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always   

volumes:
  postgres_data:
